In [1]:
import tensorflow as tf
import numpy as np

### 1. tf.where()
### 条件语句真返回A，条件语句假返回B
### tf.where(条件语句，真返回A，假返回B)

In [2]:
a = tf.constant([1,2,3,1,1])
b = tf.constant([0,1,3,4,5])
c = tf.where(tf.greater(a,b), a, b)
print("c: ", c)

c:  tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


### 2. np.random.random()
### 返回一个[0, 1)之间的随机数
### np.random.random(维度)

In [3]:
np.random.seed(1)
a = np.random.random() # 维度为空，返回标量
b = np.random.random((2,3))
print("a: ", a)
print("b: ", b)

a:  0.417022004702574
b:  [[7.20324493e-01 1.14374817e-04 3.02332573e-01]
 [1.46755891e-01 9.23385948e-02 1.86260211e-01]]


### 3. np.vstack()
### 将两个数组按垂直方向叠加
### np.vstack(数组1, 数组2)

In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.vstack((a, b))
print("c:\n", c)

c:
 [[1 2 3]
 [4 5 6]]


### 4. 生成网格坐标点(经常一起使用)：np.mgrid[] / .ravel() / np.c_[] 
### 4.1) np.mgrid[]：返回若干组维度相同的等差数组，[起始值, 结束值)
### np.mgrid[起始值:结束值:步长, 起始值:结束值:步长, ...]

In [5]:
x, y = np.mgrid[1:3:1, 2:4:0.5]
print(x)
print(y) #生成的两个数组是要保持维度相同，所以都是两行四列

[[1. 1. 1. 1.]
 [2. 2. 2. 2.]]
[[2.  2.5 3.  3.5]
 [2.  2.5 3.  3.5]]


### 4.2) x.ravel()：将x变为一维数组，“把.前变量拉值”

In [6]:
print(x.ravel())
print(y.ravel())

[1. 1. 1. 1. 2. 2. 2. 2.]
[2.  2.5 3.  3.5 2.  2.5 3.  3.5]


### 4.3)np.c_[]：使返回的间隔数值点配对
### np.c_[数组1, 数组2, ...]

In [7]:
grid = np.c_[x.ravel(), y.ravel()]
print("grid:\n", grid)

grid:
 [[1.  2. ]
 [1.  2.5]
 [1.  3. ]
 [1.  3.5]
 [2.  2. ]
 [2.  2.5]
 [2.  3. ]
 [2.  3.5]]
