### 1. 均方误差mse: loss_mse = tf.reduce_mean(tf.square(y_-y)

### 例：预测酸奶日销量y，x1和x2是影像日销量的因素。
### 拟造数据集X,Y_: y_ = x1 + x2 噪声: -0.05 ~ + 0.05 拟合可以预测销量的函数

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
np.random.seed(23455)
x = np.random.random((32, 2))
np.random.seed(23455)
y_ = [[x1 + x2 + (np.random.random()/10 -0.05)] for (x1, x2) in x]
x = tf.cast(x, dtype=tf.float32)

In [3]:
w1 = tf.Variable(tf.random.normal([2,1], stddev=1,seed=1))
print(w1)

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[-0.8113182],
       [ 1.4845988]], dtype=float32)>


In [4]:
epoch = 15000
lr = 0.002

In [5]:
for epoch in range(epoch):
    with tf.GradientTape() as tape:
        y = tf.matmul(x, w1)
        loss_mse = tf.reduce_mean(tf.square(y_-y))
    grads = tape.gradient(loss_mse, w1)
    w1.assign_sub(lr * grads)
    
    if epoch % 500 == 0:
        print("After {} training step, w1 is:".format(epoch))
        print("Loss: ", loss_mse)
        print(w1.numpy(), "\n")
print("Final w1 is: ", w1.numpy())

After 0 training step, w1 is:
Loss:  tf.Tensor(0.6589284, shape=(), dtype=float32)
[[-0.80962235]
 [ 1.4855162 ]] 

After 500 training step, w1 is:
Loss:  tf.Tensor(0.23354581, shape=(), dtype=float32)
[[-0.21869414]
 [ 1.6985074 ]] 

After 1000 training step, w1 is:
Loss:  tf.Tensor(0.13365382, shape=(), dtype=float32)
[[0.09044284]
 [1.6730996 ]] 

After 1500 training step, w1 is:
Loss:  tf.Tensor(0.08748729, shape=(), dtype=float32)
[[0.2850088]
 [1.5850053]] 

After 2000 training step, w1 is:
Loss:  tf.Tensor(0.058802005, shape=(), dtype=float32)
[[0.42477268]
 [1.4901432 ]] 

After 2500 training step, w1 is:
Loss:  tf.Tensor(0.039770197, shape=(), dtype=float32)
[[0.53275084]
 [1.4047352 ]] 

After 3000 training step, w1 is:
Loss:  tf.Tensor(0.026995476, shape=(), dtype=float32)
[[0.619081 ]
 [1.3321261]] 

After 3500 training step, w1 is:
Loss:  tf.Tensor(0.018403728, shape=(), dtype=float32)
[[0.68914163]
 [1.2717098 ]] 

After 4000 training step, w1 is:
Loss:  tf.Tensor(0.01262

### 2. 自定义损失函数
### 预测酸奶销量，酸奶成本(COST)1元，酸奶利润(PROFIT00)99元。
### 预测少了损失利润99元，大于预测多了损失成本1元，所以预测少了损失大，希望生成的预测函数往多了预测
### loss_zdy = tf.reduce_sum(tf.where(tf.greater(y,y_), COST * (y-y_), PROFIT * (y_-y)))

In [6]:
COST = 1
PROFIT = 99
epoch = 10000

In [7]:
for epoch in range(epoch):
    with tf.GradientTape() as tape:
        y = tf.matmul(x, w1)
        loss_zdy = tf.reduce_sum(tf.where(tf.greater(y,y_), (y-y_) * COST, (y_-y) * PROFIT))
    grads = tape.gradient(loss_zdy, w1)
    w1.assign_sub(lr * grads)
    
    if epoch % 500 == 0:
        print("After {} training step, w1 is:".format(epoch))
        print(w1.numpy(), "\n")  
print("Final w1 is: ", w1.numpy())

After 0 training step, w1 is:
[[2.5675967]
 [2.4931712]] 

After 500 training step, w1 is:
[[1.1613214]
 [1.1071346]] 

After 1000 training step, w1 is:
[[1.3091749]
 [1.1007752]] 

After 1500 training step, w1 is:
[[1.0584906]
 [1.0990032]] 

After 2000 training step, w1 is:
[[1.0572413]
 [1.0666682]] 

After 2500 training step, w1 is:
[[1.085192 ]
 [1.0966698]] 

After 3000 training step, w1 is:
[[1.2186614]
 [1.3010343]] 

After 3500 training step, w1 is:
[[1.1638166]
 [1.0911828]] 

After 4000 training step, w1 is:
[[1.1205218]
 [1.1888362]] 

After 4500 training step, w1 is:
[[1.2550083]
 [1.2674794]] 

After 5000 training step, w1 is:
[[1.085305 ]
 [1.1256213]] 

After 5500 training step, w1 is:
[[1.0736042]
 [1.0458753]] 

After 6000 training step, w1 is:
[[1.1864158]
 [1.0515581]] 

After 6500 training step, w1 is:
[[1.1952157]
 [1.0819554]] 

After 7000 training step, w1 is:
[[1.1945369]
 [1.0842199]] 

After 7500 training step, w1 is:
[[1.1297575]
 [1.0491594]] 

After 8000 t

### 3. 交叉熵损失函数CE: tf.losses.categorical_crossentropy(y_, y)
### 表征两个概率分布的距离，交叉熵越大两个概率分布越远，交叉熵越小两个概率分布越近。
### 例题: 二分类 已知答案y_=(1, 0) 预测y1=(0.6, 0.4) y2=(0.8, 0.2) 哪个更接近标准答案？ 

In [8]:
loss_ce1 = tf.losses.categorical_crossentropy([1, 0], [0.6, 0.4])
loss_ce2 = tf.losses.categorical_crossentropy([1, 0], [0.8, 0.2])
print("loss_ce1:", loss_ce1)
print("loss_ce2:", loss_ce2)

loss_ce1: tf.Tensor(0.5108256, shape=(), dtype=float32)
loss_ce2: tf.Tensor(0.22314353, shape=(), dtype=float32)


### 4. softmax与交叉熵结合: tf.nn.softmax_cross_entropy_with_logits(y_, y)
### 输出先过softmax函数，在计算y与y_的交叉熵损失函数。

In [9]:
y_ = np.array([[1,0,0], [0,1,0], [0,0,1], [1,0,0], [0,1,0]])
y = np.array([[12,3,2], [3,10,1], [1,2,5], [4,6.5,1.2], [3,6,1]])
y_pro = tf.nn.softmax(y)
loss_ce1 = tf.losses.categorical_crossentropy(y_, y_pro)
loss_ce2 = tf.nn.softmax_cross_entropy_with_logits(y_, y)
print(loss_ce1)
print(loss_ce2)

tf.Tensor(
[1.68795487e-04 1.03475622e-03 6.58839038e-02 2.58349207e+00
 5.49852354e-02], shape=(5,), dtype=float64)
tf.Tensor(
[1.68795487e-04 1.03475622e-03 6.58839038e-02 2.58349207e+00
 5.49852354e-02], shape=(5,), dtype=float64)
