### 1.张量
### 张量 (Tensor)：多维数组(列表)  阶：张量的维数，
### 张量可以表示0阶到n阶的数组 例：t = [[[  (表示3阶数组)

### 2.数据类型
### 1) tf.int, tf.float... : tf.int32, tf.float32, tf.float64
### 2) tf.bool : tf.constant([True,False])
### 3) tf.string: tf.constant("hello")

### 3.如何创建一个Tensor


### 1.1)tf.constant(张量内容， dtype=数据类型(可选))

In [1]:
import tensorflow as tf
a = tf.constant([1,5], dtype=tf.int64)
print(a) #依次一次输出：张量的内容/张量的形状(逗号隔开几个数字张量就是几维的，下图说明一个一维的有两个元素的张量)/张量的数据类型
print(a.dtype)
print(a.shape)

tf.Tensor([1 5], shape=(2,), dtype=int64)
<dtype: 'int64'>
(2,)


### 1.2)将numpy 的数据类型转换为Tensor数据类型
###  tf.convert_to_tensor(数据名，dtype=数据类型(可选))

In [2]:
import numpy as np
a = np.arange(0,5)
b = tf.constant([0, 5])
print(a)
print(b)

[0 1 2 3 4]
tf.Tensor([0 5], shape=(2,), dtype=int32)


### 2.1)创建全为0的张量: tf.zeros(维度)


### 2.2)创建全为1的张量: tf.ones(维度)

### 2.3)创建全为指定值的张量: tf.fill(维度，指定值)

In [3]:
a = tf.zeros([2, 3])
b = tf.ones(4)
c = tf.fill([2, 2], 9)
print(a)
print(b)
print(c)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor([1. 1. 1. 1.], shape=(4,), dtype=float32)
tf.Tensor(
[[9 9]
 [9 9]], shape=(2, 2), dtype=int32)


### 3.1)生成正态分布的随机数，默认均值为0，标准差为1
### tf.random.normal(维度, mean=均值, stddev=标准差)

In [4]:
d = tf.random.normal([2,2], mean=0.5, stddev=1)
print(d)

tf.Tensor(
[[-1.2826967  0.7812834]
 [-2.1415598  0.5052034]], shape=(2, 2), dtype=float32)


### 3.2)生成截断式正态分布的随机数(可以保证数据在均值正负两倍标准差内)
### tf.random.truncated_normal(维度，mean=均值，stddev=标准差)

In [5]:
e = tf.random.truncated_normal([2,2], mean=0.5, stddev=1)
print(e)

tf.Tensor(
[[ 0.01502815 -0.7348472 ]
 [ 0.12096345  0.5002993 ]], shape=(2, 2), dtype=float32)


### 3.3)生成均匀分布随机数 [minval, maxval)
### tf.random.uniform(维度， minval=最小值，maxval=最大值)

In [6]:
f = tf.random.uniform([2,2], minval=0, maxval=1)
print(f)

tf.Tensor(
[[0.25760627 0.89962554]
 [0.22535062 0.71650577]], shape=(2, 2), dtype=float32)
