### 4.常用函数—强制类型转换和计算

### 4.1)强制tensor转换为该数据类型
### tf.cast(张量名，dtype=数据类型)

In [1]:
import tensorflow as tf
import numpy as np
x1 = tf.constant([1.,2.,3.], dtype=tf.float64)
print(x1)

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float64)


In [2]:
x2 = tf.cast(x1, tf.int32)
print(x2)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


### 4.2)计算张量维度上元素的最小值
### tf.reduce_min(张量名)

In [3]:
tf.reduce_min(x2)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

### 4.3)计算张量维度上元素的最大值
### tf.reduce_max(张量名)

In [4]:
tf.reduce_max(x2)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

### 4.4)计算张量沿着指定维度的平均值
### tf.reduce_mean(张量名，axis=操作轴)     
### ps.axis=0表示纵向，axis=1表示横向，如果不指定axis则对所有元素进行操作

In [5]:
x = tf.constant([[1,2,3],
                 [2,2,3]])
print(x)

tf.Tensor(
[[1 2 3]
 [2 2 3]], shape=(2, 3), dtype=int32)


In [6]:
tf.reduce_mean(x)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

### 4.5)计算张量沿着指定维度的和
### rf.reduce_sum(张量名，axis=操作轴)

In [7]:
tf.reduce_sum(x, axis=1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([6, 7], dtype=int32)>

### 5.常用函数—tf.Variable
### tf.Variable(初始值)
#### tf.Variable()将变量标记为"可训练"，被标记的变量会在反向传播中记录梯度信息。神经网络训练中，常用该函数标记带训练参数

In [8]:
w = tf.Variable(tf.random.normal([2,2],mean=0,stddev=1))

### 6.常用函数—数学运算

### 6.1)对应元素的四则运算，只有维度相同的张量才可以进行四则运算

In [9]:
a = tf.ones([1,3])
b = tf.fill([1,3], 3.)
print(a)
print(b)

tf.Tensor([[1. 1. 1.]], shape=(1, 3), dtype=float32)
tf.Tensor([[3. 3. 3.]], shape=(1, 3), dtype=float32)


### 6.1.1)实现两个张量的对应元素相加
### tf.add(张量1,  张量2)

In [10]:
tf.add(a, b)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[4., 4., 4.]], dtype=float32)>

### 6.1.2)实现两个张量的对应元素相减
### tf.subtract(张量1,  张量2)

In [11]:
tf.subtract(a, b)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[-2., -2., -2.]], dtype=float32)>

### 6.1.3)实现两个张量的对应元素相乘
### tf.multiply(张量1,  张量2)

In [12]:
tf.multiply(a, b)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[3., 3., 3.]], dtype=float32)>

### 6.1.4)实现两个张量的对应元素相除
### tf.divide(张量1,  张量2)

In [13]:
tf.divide(b, a)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[3., 3., 3.]], dtype=float32)>

### 6.2)平方/次方/开方

In [14]:
a = tf.fill([1, 2], 3)
a

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[3, 3]], dtype=int32)>

### 6.2.1)计算某个张量的平方
### tf.square(张量名)

In [15]:
tf.square(a)

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[9, 9]], dtype=int32)>

### 6.2.2)计算某个张量的n次方
### tf.pow(张量名，n次方数)

In [16]:
tf.pow(a, 3)

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[27, 27]], dtype=int32)>

### 6.2.3)7.3)计算某个张量的开方
### tf.sqrt(张量名)

In [17]:
# tf.sqrt(a)

### 6.3)实现两个矩阵相乘 
### tf.matmul(矩阵1，矩阵2)

In [18]:
a = tf.ones([3,2])
b = tf.fill([2,3], 3.)
tf.matmul(a, b)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]], dtype=float32)>

### 7.常用函数—给特征和标签配对的函数: tf.data.Dataset.from_tensor_slices
### data = tf.data.Dataset.from_tensor_slices((输入特征，标签))    
### ps.对tensorflow和numpy都适用

In [19]:
features = tf.constant([12,23,10,17])
labels = tf.constant([0,1,1,0])
dataset = tf.data.Dataset.from_tensor_slices((features, labels))
print(dataset)
for element in dataset:
    print(element)

<TensorSliceDataset shapes: ((), ()), types: (tf.int32, tf.int32)>
(<tf.Tensor: shape=(), dtype=int32, numpy=12>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)
(<tf.Tensor: shape=(), dtype=int32, numpy=23>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(), dtype=int32, numpy=10>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(), dtype=int32, numpy=17>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)
