### 8.常用函数—实现某个函数对指定参数的求导运算 tf.GradientTape
### with结构记录计算过程，gradient求出张量的梯度
### with tf.GradientTape() as tape:
#### 若干个计算过程
### grad = tape.gradient(函数，对谁求导)

In [1]:
import tensorflow as tf

In [2]:
#with tf.GradientTape() as tape:
#    w = tf.Variable(tf.constant(3.0))
#    loss = tf.pow(w,2)
#grad = tape.gradient(loss, w)
#print(grad)

### 9.常用函数—枚举出每个元素并在元素前配上索引号 enumerate
### enumerate可遍历每个元素(如列表/元组/字符串)，组合为：索引 元素，常在for循环中使用。
### enumerate(列表名)

In [3]:
seq = ['one','two','three']
for i,element in enumerate(seq):
    print(i,element)

0 one
1 two
2 three


### 10. 常用函数—独热码 tf.one_hot
#### 独热编码：在分类问题中，常用独热码做标签，
#### 标记类别：1表示是，0表示非。
#### (0狗尾草鸢尾，1杂色鸢尾，2弗吉尼亚鸢尾)
#### 标签：1
#### 独热码：(0. 1. 0.) 表示百分之0的可能是狗尾鸢尾，百分之百的可能是杂色鸢尾，百分之0的可能是弗吉尼亚鸢尾

### tf.one_hot()函数将待转换数据，转换为one-hot形式的数据输出
### tf.one_hot(待转换数据，depth=几分类)

In [4]:
classes = 3
labels = tf.constant([1,0,2])
output = tf.one_hot(labels, depth=classes)
print(output)

tf.Tensor(
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


### 11.常用函数—使每个输出值变为0到1之间的概率值，它们的和为1  tf.nn.softmax
### 当n分类的n个输出通过softmax()函数，便符合概率分布。

In [5]:
y = tf.constant([1.01, 2.01, -0.66])
y_pro = tf.nn.softmax(y)
print("After softmax, y_pro is:", y_pro)

After softmax, y_pro is: tf.Tensor([0.25598174 0.69583046 0.0481878 ], shape=(3,), dtype=float32)


### 12.常用函数—assign_sub用于参数的自更新
### 赋值操作，更新参数的值并返回
### 调用assign_sub前，先用tf.Variable定义变量w为可训练(可自更新)。
### w.assign_sub(w要自减的内容)

In [6]:
w = tf.Variable(4)
w.assign_sub(1)  # 这个操作表示w-=1即w=w-1
print(w)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=3>


### 13.常用函数—返回张量沿指定维度最大值的索引号 tf.argmax
### tf.argmax(张量名，axis=操作轴)

In [7]:
import numpy as np
test = np.array([[1,2,3],[2,3,4],[5,4,3],[8,7,2]])
print(test)
print(tf.argmax(test, axis=0)) # 返回每一列最大值的索引
print(tf.argmax(test, axis=1)) # 返回每一行最大值的索引

[[1 2 3]
 [2 3 4]
 [5 4 3]
 [8 7 2]]
tf.Tensor([3 3 1], shape=(3,), dtype=int64)
tf.Tensor([2 2 0 0], shape=(4,), dtype=int64)
